name: Gitflow Hotfix

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - hotfix-start
          - hotfix-finish
      version:
        description: 'Hotfix version (e.g., 0.1.1)'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  hotfix:
    uses: dataliquid/github-actions/.github/workflows/gitflow-hotfix.yml@1.0.0
    with:
      action: ${{ inputs.action }}
      version: ${{ inputs.version }}
      java-version: '17'
      java-distribution: 'temurin'